from langchain_core.prompts import ChatPromptTemplate,MessagesPlaceholder

from agentutils import get_llm



reflection_prompt=ChatPromptTemplate.from_messages([
    ( "system",
    "You are a viral twitter influencer grading a tweet. Generate critique and recommendations for user's tweet."
    "Always provide detailed recommendations, including requests for length, virality, style etc.",
      ),
MessagesPlaceholder(variable_name="messages"),  # When you invoke this prompt, put the list of messages supplied under the name messages into this slot.
])

generation_prompt=ChatPromptTemplate.from_messages([
    ( "system",
        """You are a Twitter/X writing critic.

Your task is to critique the latest tweet generated by the assistant.

Do NOT rewrite the tweet.
Do NOT provide a new tweet.
Do NOT act as the writing assistant.

Instead, identify what is good, what could be improved, and give specific recommendations about:
- clarity
- conciseness
- technical accuracy
- hook
- engagement
- tone
- virality
- length

Your response should contain only critique and recommendations."""
     ),
    MessagesPlaceholder(variable_name="messages"),

])

llm=get_llm()
generate_chain=generation_prompt | llm
reflection_chain=reflection_prompt | llm
